### ISSUE TITLE
create /ping endpoint

### ISSUE THREAD

**Issue by baldur** [polygon-city/building-database#101]
ideally something that exercises node and potentially mongo db for loadbalancer to know if the instance is up and running.

something like /ping would be great althought it can be anything

**Comment by robhawkes** [comment]
No problem, I'll get that added in.

Are there any specific HTTP codes you want to be returned, aside from 200 if all is ok?

**Comment by baldur** [comment]
200 suffices ... if you app is unable to respond the other codes will come from the nginx frontend

**Comment by robhawkes** [comment]
7628498 adds a ping endpoint for you – let me know if you need it to do anything differently.
