### ISSUE TITLE
Upload button hangs on invalid model

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#107]
To reproduce:
Attempt to upload a non-model file (I dropped a directory on the "Choose file" button)

Results:
Upload button changes to "Uploading…" and becomes inactive. Page does not change or progress to the next page.

Expected results:
The upload button won't say "Uploading" if no upload activity is occurring – should probably also show an error message onscreen, maybe do a validity check when a file is chosen?

**Comment by robhawkes** [comment]
c57b0fb fixes this (after multiple attempts to push through the GitHub DDoS). I had a bit of the file-type checking set after another check with exited the upload process without resetting the state. Should be ok now.
