### ISSUE TITLE
Add ability to drag, rotate and scale the 3D model using the mouse when setting location

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#18]

**Comment by robhawkes** [comment]
This is going to require some fairly significant changes to ViziCities that'll require a bit of time to sit down and work out how to fit it in with the rest of the platform. I'd argue for deferring this until after the initial launch. Otherwise, I could hack something together that allowed for some sort of linkage with the mouse and the 3D view, though probably not 1:1 (ie. ray-casted point from mouse).

**Comment by robhawkes** [comment]
8ae9f12 is an initial pass at mouse-based controls for moving the building. It occurred to me that all I needed to do was lock the building to the camera as that already handled the ability to pan around the world. The location fields update automatically as you move the building (and camera) around.

I've not added any mouse-based controls for scale yet, though theoretically I add a modifier key to do it on mouse scroll.

**Comment by robhawkes** [comment]
0b138a4 adds basic scale and rotate buttons to the `/add/location` page on top of the existing ability to change the angle and scale by scrolling on the relevant form fields.

**Comment by robhawkes** [comment]
I've no current plans to add more to this issue unless we feel the current situation isn't working – the buttons for angle and scale are simple but they work. I propose leaving things as is for v1 (basic dragging of the model with buttons for scale and angle) and deferring anything more advanced to v2 once we better understand the pain-points of the whole `/add/…` flow.

Thoughts?

**Comment by meetar** [comment]
Agreed

**Comment by robhawkes** [comment]
Awesome, I'll close this and we can open a new issue for v2.
