### ISSUE TITLE
Consider linking with OSM before setting location and using that as starting location

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#19]

**Comment by robhawkes** [comment]
I've been thinking about this and putting the OSM linkage before setting the location would certainly help by defining a good guess at a starting location, though it does then require finding the location twice (once at a global scale to find the right OSM ID, and again at a local scale to set the actual location). 

There's nothing inherently wrong with this approach but it does feel a little less tidy compared to finding the global location beforehand and then just running a small static OSM query around that location to find the nearby entities which you can click on. This is why the OSM linking map isn't currently moveable as touched on in #23, as if there isn't an item nearby the location then it can't be linked to the building.

The benefit of linking with OSM beforehand is that you can use the OSM data to pre-populate location and potentially even take a stab at the building orientation (though the latter opens a big can of worms).

I'm curious to hear your thoughts on the 2 approaches here.

**Comment by meetar** [comment]
Yeah, starting with global location is cleaner and simpler. I'm happy to carry on as we are.

**Comment by robhawkes** [comment]
Cool, I'll close this for now and we can reopen it again in the future if things change.
