### ISSUE TITLE
Model material is black when textures cannot be found

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#20]
It's hard to avoid materials not being found but we can definitely have a better default material before textures are loaded / when materials don't load.

**Comment by robhawkes** [comment]
I've had a look into this and it's not a simple fix – I'd likely need to customise the ColladaLoader module in Three.js and even then that only solves the problem for collada models. A better approach might be to detect missing textures during the upload process and do something about it then before it gets to the point of outputting the model.

Otherwise, perhaps there's a way to detect a missing texture at run-time (before ColladaLoader) and enforce a default material if so.

**Comment by robhawkes** [comment]
This is still proving tricky but 362d9a5 adds a rough method of replacing unloaded textures with a solid colour should they not load within a second. We need a better way of doing this but at least the models look a lot nicer now!

**Comment by meetar** [comment]
Yeah, this method works for me for the moment – we might shelve this until we have a better idea idea how frequently we'll run into a .dae with broken textures.

**Comment by robhawkes** [comment]
Ok, let's do that for now and re-open it if it becomes a concern again.

**Comment by meetar** [comment]
Not positive this is the same issue, but here's another .dae loading as all black: https://github.com/polygon-city/building-database/blob/models/test/models/tajmahal.dae

I don't know .dae very well, but I don't see any material or texture references in this file at all – so in this case it might not trigger the "missing materials" condition.

**Comment by robhawkes** [comment]
The method currently used to change the materials to grey isn't very robust so it's likely not suitable in its current form. I'll have a think about a better way to handle this using the tajmahal.dae model as an example.

**Comment by robhawkes** [comment]
Before I sink time into collada fixes here I'm going to wait and see if moving to OBJ (or some other) model format in #90 also helps with materials.

**Comment by robhawkes** [comment]
2f139a5 adds experimental support for OBJ-based models rather than collada on the building detail page (no where else just yet). Initial results are good and it's meant that I don't need to do any of the fancy material checking (you can just load it in as a single colour regardless), plus the scaling seems to be handled better (assuming models are created with metre units). Also, the OBJ model loader is far simpler so we can customise it should we want.

If we go with OBJ then I'll need to make sure `/add/location` uses OBJ too for consistency with setting scaling, etc.

One potential download to using OBJ is that I've needed to create a single custom element in the KML definition to provide the OBJ file. I think this is ok as we only need it internally (maybe for ViziCities too) and it doesn't overwrite any standard elements.

**Comment by robhawkes** [comment]
Now that `/add/location` also uses OBJ we can close this issue if the models that were appearing black before now look ok. Can you confirm?

**Comment by robhawkes** [comment]
I'm going to close this under the assumption that it's fixed now. If not, we can reopen.
