### ISSUE TITLE
Search for buildings using an interactive map

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#22]
It would be useful to be able to search for buildings using a map as this is far more intuitive than manually entering locations.

**Comment by robhawkes** [comment]
This is likely going to be partially or fully implemented by #33

**Comment by robhawkes** [comment]
While the new browse and search interface added during #33 is a map, it still doesn't have the ability to dynamically update the buildings as you move and zoom the map view. This is going to require some thought as we'll need to think of a nice way to handle the (hopefully) large number of buildings that will be in view at zoom levels that display whole countries or the world.

**Comment by robhawkes** [comment]
8b9a8abcccec9016f45bf5c2167eb2d02c82805e adds a `/browse/all` endpoint that is experimenting with an interactive map-based approach to discovering buildings. It shows all buildings in the system rather than filtering or paginating them.

**Comment by meetar** [comment]
I haven't looked at your implementation, but assuming you're using one of mongoDB's geo indexes, would you be able to query for buildings per-tile? And then possibly sort by e.g. downloads, and only take the first x number of buildings?

**Comment by robhawkes** [comment]
I don't think the Mongo geo functionality has tile logic built in but you can certainly pre-calculate the tile coordinate bounds and use that to filter the query. From there you can do whatever sorting and other filtering you wish.

The current approach works quite nicely but it'll hit issues when we have many thousands of buildings. Query per-tile or by the map-view bounds will allow us to be a bit more intelligent but then we'd need to filter the results down somehow (by downloads, cap to X most recent, etc). Either way, it'd mean some buildings aren't displayed.

Another approach could be to use your per-tile idea and instead show a count of buildings in that tile rather than retrieving them, that way we include all the buildings. Once you get to a certain zoom we can switch from counts to all the actual buildings in that area.

**Comment by robhawkes** [comment]
The `/browse/all` endpoint should be included in the v1 milestone. All that needs to be done is for a link to it to be placed somewhere on the website.

**Comment by bcamper** [comment]
I think it would be ideal to include a tile-compliant query mode, which could just construct a bbox based on tile coordinates and use the same underlying implementation. We can break out to a separate issue if we need.

**Comment by robhawkes** [comment]
We could use the same solution for #49 as it's a near identical situation, or will at least overlap a bunch.

**Comment by bcamper** [comment]
Yep - a bbox-based endpoint (with reasonable limit on bbox size) and
tile-based endpoint would both be useful.

**Comment by robhawkes** [comment]
716ab32 adds a new `/api/buildings/bbox/:west,:south,:east,:north` endpoint that returns buildings intersecting a given lat/lon bounding box. There aren't any limitation on the size of the bounding box or the number of returned buildings yet.

**Comment by robhawkes** [comment]
c8a8c7f adds an `/api/buildings/near/:lon,:lat,:distance` endpoint that returns buildings within a distance of a specific point. Distance is in metres.

**Comment by robhawkes** [comment]
7f87e4e adds an `/api/buildings/tile/:x,:y,:z` endpoint that returns buildings intersecting a specific tile. We may need to tweak this to account for buildings that overlap tile edges.

**Comment by robhawkes** [comment]
b3c5305 adds an explore link in the navigation to the `/browse/all` interactive map endpoint. I'd consider this issue closed in that regard and move the discussion about dynamically updating the browse map into #49.

**Comment by robhawkes** [comment]
If no one objects, I'm going to close this issue under the assumption that the more dramatic changes will be addressed by #82 in v2.

**Comment by meetar** [comment]
Agreed

**Comment by robhawkes** [comment]
Cool, I'll close this then and we can open a new issue if #82 doesn't cover it.
