### ISSUE TITLE
500 error uploading .dae

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#27]
![screen shot 2015-01-13 at 6 19 28 pm](https://cloud.githubusercontent.com/assets/459970/5731389/bc83b7a4-9b50-11e4-9654-c09a8f595716.png)

file in question:
http://tf3dm.com/3d-model/killer-whale-80576.html

copied out of the Chrome console with horrible text formatting:

    jquery.js:8623 POST http://localhost:3000/api/buildings 500 (Internal Server Error)
    jquery.js:8623     n.ajaxTransport.k.cors.a.crossDomain.send
    jquery.js:8152 n.extend.ajax
    add:75 (anonymous function)
    add:93 500
    add:94 error
    add:95 Internal Server Error

It's not a very good killer whale tbqh

Looks like some sort of CORS issue related to the jquery upload function? Not sure why it would be a problem here – this looks like it might be the same thing that we saw with the zips, but I'm not sure.

**Comment by meetar** [comment]
And once this has happened, uploads are effectively broken. Can't upload the same zip I just uploaded. ¯\_(ツ)_/¯

**Comment by robhawkes** [comment]
I'm unable to replicate this with the same collada file, it uploads correctly and moves onto the add location step. The server should output something, perhaps in the terminal or as the response to the AJAX request. Do you see anything useful in the AJAX response body in the browser console / network panel?

**Comment by meetar** [comment]
The server window just says: `POST /api/buildings 500 12.450 ms - 2335`
The network window says: `	GET	200	application/javascript	Other	242 KB	14 ms	
buildings	POST	500	text/html	jquery.js:8623	2.5 KB	15 ms`
And the console only has what I pasted above… I'll try some more tests and try to get it to say something more useful.

**Comment by robhawkes** [comment]
I'm now able to replicate this quite nicely, simply by uploading a building and then trying to upload another one. The second upload fails with a 500 error. This didn't happen before so clearly something has changed, most likely some logic I added recently which deletes the temporary files added during the upload process.

**Comment by robhawkes** [comment]
Confirmed fixed with ac089dd
