### ISSUE TITLE
Occasional texture/uv issue when uploading dae in a zip

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#28]
the WTC model specifically: 
![screen shot 2015-01-13 at 5 51 12 pm](https://cloud.githubusercontent.com/assets/459970/5731061/8479f718-9b4d-11e4-8685-7be719b6c857.png)

It's always the same faces, too. One Canada Square doesn't have that problem. Haven't tried any other models yet.

**Comment by robhawkes** [comment]
I'm using the default Three.js collada importer so it's possibly a problem with that / this model specifically. The model renders fine outside Three.js so it does point toward the collada import script doing something wrong.

I'm also curious if this happens with the Three.js obj importer too, I'll look into that.

**Comment by robhawkes** [comment]
This looks like it might be [a collada-only issue, specifically with models exported from SketchUp](https://github.com/rmx/threejs-collada/issues/16). Still no closer to a fix but if this is the case then when we try uploading as an obj file then the textures should be ok.

**Comment by robhawkes** [comment]
I just tried converting the WTC model to OBJ format to see if the problem still exists and even in MeshLab the UV coordinates are all funked up. If we can get a clean OBJ export from the collada file then we can give it a go.

**Comment by robhawkes** [comment]
Closing this as we currently force all buildings to render with a flat material for now (though textures are provided within the zip download). We can look at it again in v2 should it resurface, though I think us now using OBJ for display will have fixed some of this.
