### ISSUE TITLE
handle missing texture file in .dae

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#29]
to reproduce:
- upload Killer_Whale.dae (not as a zip), ensuring server doesn't have access to Killer_Whale_D.tga
- set a location
- hit back

results:
- page freezes, then crashes -
- upload functionality breaks:
POST /api/buildings 500 13.785 ms - 2335
jquery.js:8623 POST http://localhost:3000/api/buildings 500 (Internal Server Error)

Looks like the same error as https://github.com/polygon-city/building-database/issues/27

**Comment by robhawkes** [comment]
I can replicate this! I don't think it's related to the missing texture but something weird is going on. I dug into the HTTP 500 and the response given to the browser is along the lines of:

`ENOENT, open 'tmp/44902c29eb82c3a79daa304ca895678c.dae'`

So for some reason the app is getting itself into a mess when you click back during the add building process and it stops putting uploaded files into a temporary directory until you restart the app.

**Comment by robhawkes** [comment]
It looks like the file doesn't even make it into the upload router handler when this happens which points toward something else, perhaps a bug with the file-upload module (multer). I'll look into it.

**Comment by meetar** [comment]
Where did you find the error? Is that buried in the console somewhere?

**Comment by robhawkes** [comment]
Yeah, it's in the network pane of the developer tools. In there you'll see the failed POST request in red and if you click it, then click response, you'll see some HTML output containing the failure message. I'm going to add another issue to tidy up those AJAX failure messages as the HTML shouldn't be outputted for those really.

**Comment by robhawkes** [comment]
Closing this as it's the same issue as #27
