### ISSUE TITLE
catch enter key in "move to" field 

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#30]
to reproduce:
- upload a model
- on "Set building location" page, type in the "Enter name of place to move to" field and hit enter

results:
- "Set location" button at bottom of page is onClicked
- next page is loaded, with default location

expected results:
- something will be selected in the list of dropdowns (perhaps the item with the highest match score?)

**Comment by robhawkes** [comment]
This is an interesting one, I never tried pressing enter before using the arrow keys to highlight one of the suggested options. Catching the enter key on the move to field should allow us to do something a bit more intelligent here.

**Comment by robhawkes** [comment]
This has been roughly implemented via 034a015
