### ISSUE TITLE
overpass error on "back"

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#32]
to reproduce:
- upload a model, progressing through to the "Link building to OpenStreetMap" page
- hit "back" in the browser

result:
- an error alert appears, reading "An error occured during the execution of the overpass query!
<p>Request rejected. (e.g. server not found, request blocked by browser addon, request redirected, internal server errors, etc.)</p><p>Error-Code: error (0)</p>"

note:
chrome only, results are inconsistent – currently unable to reproduce. testing with various chrome extension combinations.

**Comment by robhawkes** [comment]
I'm unable to replicate this at the moment though the error looks like a standard aborted/failed AJAX request which [the Overpass library has decided to override](https://github.com/tyrasd/overpass-turbo/blob/ee7be32f731f0d96c43361545946912be6e37434/js/overpass.js#L590). I can probably remove this from the Overpass library (we have to build a slightly custom version anyway) and prevent it from going overboard with the reporting.

**Comment by robhawkes** [comment]
I've disabled the Overpass error popup in 7452c02 and also [created a proper fork of the Overpass library](https://github.com/polygon-city/overpass-turbo) so we can track and build the changes properly. Let me know if you see any popups after updating to this version.
