### ISSUE TITLE
Tracking design progress

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#33]
(Re)design progress is currently happening in the [redesign tree](https://github.com/polygon-city/building-database/tree/redesign). So far the majority of focus has been on the homepage and browse page, neither of which are at a final stage.

**Comment by robhawkes** [comment]
3dcb3bd5846af88200ebdba0c7aae6d58694cc93 in the redesign tree adds massive improvements to the browse and search results areas. Still some tweaking left to do though.

**Comment by robhawkes** [comment]
I've pushed significant design changes in the redesign tree for most of the site now, most notably the individual building pages. Still got some bits and pieces to tidy up in general but I'm quite happy with how the core concept is looking now it's applied site-wide.

**Comment by robhawkes** [comment]
The redesign tree has matched and in some areas surpassed the master branch for functionality so I've merged it in with ff89c79.

**Comment by bcamper** [comment]
:clap: :clap: :clap: I like it!

**Comment by robhawkes** [comment]
Glad to hear it! We can tweak, change and tidy things as we go but it certainly looks a lot more like a proper site now. We're getting there!
