### ISSUE TITLE
Moderation of buildings

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#37]
We need to consider how the moderation of buildings should be handled. Possible approaches could involve manual review of buildings after addition, reactive processing based on user reports, or even requiring some kind of manual check before addition.

It would be good to hear your thoughts on what our responsibilities should be here, then we can look at how to implement that.

**Comment by meetar** [comment]
Yeah, a flagging mechanism which notifies an admin once a model gets some number of flags is probably the simplest and most scale-proof – if the site gets huge, you just increase the threshold. Adding limits to behaviors to prevent unwanted bot activity is probably wise as well.

This all presupposes some kind of admin-only UI options, and possibly an admin utility page to do things like remove or hide an upload or uploads, ban a user, etc, along with batch actions. My brief experience maintaining a wiki showed me that spam bots are remarkably clever and persistent, even for totally uninteresting sites with zero traffic.

Of course there will always be trolling, spam, and malcontents of one stripe or another. It will be important to have a clear TOS including standards of acceptable use – and to allot person-time toward the maintenance of the site once it's launched.

**Comment by robhawkes** [comment]
Ok, I've set up #41 to track the creation of an admin area. We can make sure it includes the ability to perform moderation tasks and to highlight particular buildings that have been reported so many times.

I hadn't thought about TOS so I've set up #42 to track its addition.

**Comment by robhawkes** [comment]
d56c14e adds initial support for the storage of building reports in a database and the viewing of them via the admin panel.

**Comment by robhawkes** [comment]
I think this feature has got to the point where we need to flesh out exactly what we want it do for the v1 milestone. As things stand, building reports are stored in the database and are viewable via the admin interface. They're also emailed to a specific address as per the configuration file.

Do we want more for v1?

**Comment by meetar** [comment]
This sounds good – I'd be happy to launch with this and adjust as needed later.

**Comment by robhawkes** [comment]
Awesome, I'll close this then and we can open other issues should specific things need tweaking.
