### ISSUE TITLE
How should duplicate buildings be handled?

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#38]
Duplicate buildings can't be avoided and should potentially be encouraged in an effort to have a range of quality and styling options available.

How should we handle duplicates?
- Should they be detected and grouped?
- If so, how are duplicates detected?
- How should duplicates be represented in the search and browse results?
- Should a "favourite" be selected to prioritise in search results? Perhaps based on download count of editorial review.

**Comment by meetar** [comment]
> Should a "favourite" be selected to prioritise in search results? Perhaps based on download count of editorial review.

I like this idea – an editorial override is definitely a good idea, to handle cases where for whatever reason the most popular download isn't our preferred model (jokes, spam, trolling, etc)

**Comment by robhawkes** [comment]
I've set up #41 to track the progress of an admin area that will be able to handle tasks like editorial overriding.

**Comment by robhawkes** [comment]
Closing this in anticipation of featured buildings being added by #41 to prioritise buildings in results.
