### ISSUE TITLE
Create an admin interface

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#41]
We're going to need some kind of admin interface for keeping an eye on the system, moderating uploads and doing other tasks such as giving certain buildings editorial override in the various browse and search rankings.

**Comment by robhawkes** [comment]
Things the admin interface should be able to handle:

- User management
 - [ ] Edit
 - [ ] Ban
- Building management
 - [ ] View reported buildings
 - [ ] Edit
 - [ ] Delete
 - [ ] Award editor's pick

**Comment by robhawkes** [comment]
024d2f1 is the start of this implementation, introducing an admin area and the ability to see all buildings and users.

**Comment by robhawkes** [comment]
92759e7 is the start of being able to hide buildings from view without deleting them. So far you can toggle the `hidden` flag in the database via the admin panel, though this currently has no effect on where the building is shown. That's next.

**Comment by robhawkes** [comment]
ec31483 prevents hidden buildings from appearing publicly anywhere in the system.

**Comment by robhawkes** [comment]
f3e407a adds a ban field to the user database model and hooks up the admin interface to actually ban people. This currently has no effect on the rest of the system, aside from flipping a flag in the database.

**Comment by robhawkes** [comment]
771ce16 prevents a banned user from logging in. There are no other ramifications to being banned just yet (ie. the buildings they've created will show up and their profile will be visible).

**Comment by robhawkes** [comment]
733280a adds building editing from the admin interface, and admin access to the standard location and OSM-linkage pages.

**Comment by robhawkes** [comment]
218b781 adds a highlight button in the admin area that prioritises a building in browse, search and API results. We'll likely want to tweak the behaviour of the prioritisation and how it's communicated to the user (if at all).

**Comment by robhawkes** [comment]
d56c14e adds a building report page to the admin area.

**Comment by robhawkes** [comment]
I'm debating holding out on adding a delete building feature to the admin area as it's a bit… permanent and the hide building option will probably allow us enough flexibility for now.

What do you think?

**Comment by bcamper** [comment]
I think that's fine for v1.

**Comment by robhawkes** [comment]
Alright then, I'm going to close this issue and we can raise a new one should specific changes to the admin interface need to be made for v1.
