### ISSUE TITLE
Signup: duplicate email error message

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#44]
This is fairly niggling, but if you attempt to sign up with an email address already in the db, the error message is "User already exists" rather than eg "That email address has already been registered to another user" or somesuch.

**Comment by robhawkes** [comment]
I'm unsure how to handle the sign-up messages as from one side we obviously need to make it clear why you can't sign up, but on the other it feels like a bad thing to provide a method of working out who has signed up in the past (by providing someone else's email). Interestingly, we could make usernames the unique ID we check against, which would help with #46.

**Comment by robhawkes** [comment]
89e46e3 adds some improvements here.
