### ISSUE TITLE
Location validation

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#45]
I can't find where we were talking about this, feel free to close this issue if it's redundant :)

Input validation on the building location lat/long fields doesn't accept values from search results. (You mentioned that was something related to a library you're using?)

To reproduce:
1) upload a building
2) in "Move to:" field, type NYC (the first result is in Camden Town, naturally - probably a punk clothing shop)
3) click "Set location" button

result:
an error popup with the text "Please enter a valid value" etc

expected result:
next page in the flow

**Comment by robhawkes** [comment]
I think #30 is the related issue. I clearly must have forgotten to move the fix over during the redesign update so I'll look into that and re-fix it!

**Comment by robhawkes** [comment]
As an aside, we probably need a better way to validate location as the current method of using the `step` parameter of the `input` element makes things really clunky for actually moving things around.
