### ISSUE TITLE
Simpler urls?

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#46]
Currently the pages for a given user or building are things like /user/54ca8a9b45034ea387e53710 and building/54ca8a9b45034ea387e53710/ rather than something like /user/username or /building/building-name-10101 … are the hashes useful as a security measure?

If it's not a huge pain to implement, it might be worth exploring the option of plaintext human-readable URLs to increase ease of navigation, shareability, and so on.

**Comment by robhawkes** [comment]
I've been wanted to look at this for a while. The hash at the moment is actually the ID from Mongo, which arguably isn't the greatest thing to expose publicly. The problem is that usernames aren't unique in this system so we'd have to either find a way to attach some unique identifier along with the username, which complicates the URL, or make usernames unique, which complicates the registration system.

I don't mind looking at making usernames unique if that sounds like a better option for a clean URL. What do you think?

**Comment by robhawkes** [comment]
Ok, so it's simple enough to create a unique index on both the email and username fields so that solves part of the problem.

```
db.users.ensureIndex( { email: 1 }, { unique: true } )
db.users.ensureIndex( { username: 1 }, { unique: true } )
```

This currently causes a crash on signup with a username that already exists:

```
MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: building-database.users.$username_1  dup key: { : "robhawkes" }
```

I'm looking into this now.

**Comment by robhawkes** [comment]
814b1ec adds unique usernames and emails, assuming the correct Mongo indexes have been added (as per above and the readme). Next up is using the unique usernames as a URL identifier.

**Comment by robhawkes** [comment]
155a00c moves to using usernames instead of ID within URLS (eg. `/user/robhawkes`)

**Comment by robhawkes** [comment]
Buildings are going to take a little more thought, as clearly the names aren't unique and the ID string is too long to combine. It would make sense to generate some kind of short ID to add to the end of the (potentially cropped) building name.

**Comment by robhawkes** [comment]
55afec6 adds short building slugs (only applied to new buildings) with the intention of eventually having URLs such as `/building/X1CwcSNU/one-world-trade-center`. It doesn't matter what the end of the URL actually says as it's only the slug that is the unique identifier.

Unfortunately, this requires the database to be started from scratch as you can no longer access the building page using the long ID. You'll also need to set the `building.slug` index in Mongo.

```
db.buildings.ensureIndex( { slug: 1 }, { unique: true } );
```

**Comment by robhawkes** [comment]
069ac0a moves to a new building URL system in the format `/building/:slugId/:slugName` (eg. `/building/myy6a9BL/one-canada-square`. The `:slugName` is optional and can even be left out, however it is used across the site to increase readability for the user.

This commit changes the structure of the way slugs are stored in the database so the index above should be deleted and replaced with the following:

```
db.buildings.ensureIndex( { "slug.id": 1 }, { unique: true } );
```

Also, any existing buildings won't work with the new approach so you'll want to clear them from the database (ps. MongoHub is good for managing it in a GUI).

**Comment by robhawkes** [comment]
Further to our discussion about simpler URLs last week, while we seem to be ok with the current approach for now, it seems that there are some ramifications to consider further down the line.

For example, if the building URLs aren't truly unique (you can change anything after `/building/:slug_id/…") then does that have an effect on how search engines look at Polygon City (ie. duplicated content).

**Comment by robhawkes** [comment]
I don't have any specific plans to improve this beyond the current implementation, unless we think there's something particular that's missing for V1. Are you happy for this to be closed for V1?

**Comment by bcamper** [comment]
Works for me.
