### ISSUE TITLE
Change search/near parameters when map changes

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#49]
When following the "See nearby buildings" link from a building page, the default search range appears to be 1000 (guessing m), judging by the URL, eg /search/near/-0.14031/51.53615/1000 .

If there are no buildings nearby, none are displayed. If the map is manipulated to show an area with buildings, they aren't displayed either because the search parameters aren't changed. Perhaps the range parameter could vary with the zoom level? Or the functionality changed to explicitly return buildings within the current map view? … or is that effectively what is described in #22 and implemented in https://github.com/polygon-city/building-database/commit/8b9a8abcccec9016f45bf5c2167eb2d02c82805e?

**Comment by robhawkes** [comment]
What I could do here is create a little JSON endpoint for retrieving nearby buildings and load them in dynamically based on the URL. That way we can use the History API to update the URL as you move and just re-request the buildings JSON without a full refresh. However, this would kind of make the distance value unnecessary.

Another approach could be to simply disable movement of the map.

Regardless, I think some kind of indication of the distance and centre point would be useful too.

**Comment by meetar** [comment]
My vote's with the first option – it's possible to get the bbox of the current map view, right? Would that make other API queries unnecessarily complex? The centre-point/distance query would be a nice option, at least for the API… cc @bcamper

**Comment by robhawkes** [comment]
Getting the bbox shouldn't be an issue in Leaflet. I don't see how it'd cause any issues with other APIs beyond requiring a new `/api/search/bbox` endpoint. I can implement an `/api/search/near` one at the same time that replicates the current distance-based search behaviour but as an API.

**Comment by robhawkes** [comment]
Tracking for new API endpoints can be found in #22

**Comment by robhawkes** [comment]
Is this part of the v1 milestone? The API updates in #22 pave the way for this, but there's still quite some implementation changes to the `/search/near` endpoint to become dynamic.

**Comment by meetar** [comment]
To clarify, wouldn't the "search near" map interface effectively be the "browse all" map interface, but starting from a certain location?

**Comment by robhawkes** [comment]
Yeah that's the plan (and they could be merged), though right now they are separate due to neither adopting a dynamic approach similar to the one discussed here (the `/browse/all` endpoint loads in every building on page-load and clusters them).

**Comment by meetar** [comment]
Per email: we will improve what we have for v1 and will re-organize and implement dynamic maps for v2.
