### ISSUE TITLE
Prepopulate "Report a building" form email field when logged in

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#50]
…or perhaps remove that field entirely, require a login to report a building, and require a confirmed email address to register?

Arguments for:
- reduce the potential for accidental mis-entry of the email
- prevent users from attaching others' emails to a report
- slight barrier to erroneous reporting

Arguments against:
- slight barrier to legitimate reporting

**Comment by robhawkes** [comment]
I think we should keep the email field so there's no barrier to submitting reports, though it makes sense to pre-populate this if you're logged in. I'll add this in shortly.
