### ISSUE TITLE
Add building tagging

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#52]
It'll be useful to have some kind of tagging functionality so common attributes can be attached to buildings. It's possible that some of this can be derived from OSM.

Some examples include:

- Style (if this can even be quantified)
- Method (what method was used to make it: hand-made, lidar, etc)
- Source  (where the building data originally came from)
- Material (what kind of materials: photo-realitsic, block colour, none, etc)

**Comment by robhawkes** [comment]
This isn't that tricky from an implementation standpoint, though we should know what kind of tags we want before I do that. Another question is do we want freeform tags or predefined ones.

**Comment by meetar** [comment]
Working draft of attributes here: https://docs.google.com/a/mapzen.com/document/d/1WBQXpXwDHNYWHuuNKzifsfWFDlf3gOHAPbUIpI_PAaE/edit

**Comment by robhawkes** [comment]
058aad7 adds a few of the attributes that I imagine the user providing (on the `/add` page). I've not yet added any that we'd want to use internally, or the address attribute.

**Comment by robhawkes** [comment]
I'm not planning on adding any more tags for v1, aside from stuff that crops up with the batch upload stuff or Nominatim updates. I'm going to close this for the sake of a release but we can (and should) revisit in the future if specific tags are missing.
