### ISSUE TITLE
Improving error handling (not crashing, reporting, etc)

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#56]
During early development it made sense to quickly crash on an error and not to handle it correctly. Now we're nearer release the error-handling needs to be looked into.

- How should errors be handled so they don't crash the app?
- Where do we log the errors?
- How can we be notified of errors?
- Are there any errors that *should* crash the app?
- How will the app be restarted should it crash?

**Comment by robhawkes** [comment]
In the past I've used things like [Sentry](https://getsentry.com) to track errors and notify me as soon as they occur. I don't know what you guys use in production but this wouldn't be hard to implement if there isn't something else you prefer.

**Comment by meetar** [comment]
I believe https://circleci.com/ and http://travis-ci.com are both in use here, but i don't know if they meet your needs here. cc @bcamper

**Comment by robhawkes** [comment]
They'll do the job for automating the testing as we deploy changes (see #57). In this case I'm talking more about runtime error and exception tracking (and notification). I've used Sentry previously with good results, though I don't think it has a free account. I'll have to look and see what alternatives are around.

**Comment by robhawkes** [comment]
There's also [TrackJS](http://trackjs.com/), which looks good.

**Comment by bcamper** [comment]
I will defer to @baldur on his preferences here, so we don't end up using 3 different services that do the same thing for 3 different apps :)

**Comment by robhawkes** [comment]
297cd75 introduces a range of improvements to error handling and logging, though we're still missing a system-wide approach to the process of reacting to crashes.

**Comment by robhawkes** [comment]
I'm going to close this as it was more a placeholder so I didn't forget to tweak a few things and bring it up. With the error improvements and the Chef progress (assuming it has auto-restart on crash) we should be much better placed now.

Anything specific can be opened in a separate ticket so it's easier to keep track of.
