### ISSUE TITLE
Compile example buildings for testing

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#58]
We've mentioned previously that we should compile a range of buildings that cover the various things we should be supporting. This issue will track the collection of example buildings that vary in source file format, polygon count, style, materials, size, etc.

For this purpose it's not required that the buildings have a true location and scale attached to them as we can make those up. The important thing is having a range of buildings to use for testing.

**Comment by meetar** [comment]
I'll start a collection in the repo.

**Comment by robhawkes** [comment]
Seeing as I've got a local branch with some early testing progress in a `tests` directory, we might as well put the models in `test/models` or some such.

**Comment by meetar** [comment]
added a few models to /test/models in new branch models https://github.com/polygon-city/building-database/tree/models

**Comment by meetar** [comment]
Old Google 3D Warehouse models are here: https://3dwarehouse.sketchup.com/search.html?redirect=1&uq=1837918219777584484005865

**Comment by robhawkes** [comment]
We should be able to use building models created from CityGML exports during testing too – see #85

**Comment by robhawkes** [comment]
I've removed the v1 milestone as we've got a lot of buildings to test with now (including CityGML) and I see this as an ongoing task rather than something we'll complete.

**Comment by robhawkes** [comment]
I'm going to close this as the compilation of test buildings is an ongoing process now, especially with the new CityGML import.
