### ISSUE TITLE
Crash on signup: TypeError: Cannot read property 'fromAddress' of undefined

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#63]
In the 'chef' branch, when signing up for a new account:

    /srv/buildingdb/releases/8dbe12cbc5d54bff17f3f9192e32c5104a7463ae/controllers/auth.js:118
                if (!config.email.verify.fromAddress) {
                                        ^
    TypeError: Cannot read property 'fromAddress' of undefined
    at /srv/buildingdb/releases/8dbe12cbc5d54bff17f3f9192e32c5104a7463ae/controllers/auth.js:118:41
    at fn (/srv/buildingdb/releases/8dbe12cbc5d54bff17f3f9192e32c5104a7463ae/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/srv/buildingdb/releases/8dbe12cbc5d54bff17f3f9192e32c5104a7463ae/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

**Comment by meetar** [comment]
@baldur has either solved the problem or found a way to keep us from seeing it – @robhawkes will have a better idea of which this is: https://github.com/polygon-city/chef-buildingdb/commit/de1037598f41736a5386fdb7e87e1bdf83164239

**Comment by robhawkes** [comment]
The fix looks around right. When I added the new user verification stuff it also added in a couple more configuration options so that's what caused it.

Has this solved the signup crash?

**Comment by robhawkes** [comment]
I'm going to close this, assuming the problem has gone now the right config is in place. Reopen it if not!
