### ISSUE TITLE
MongoError: auth failed

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#65]
I believe this is a problem with my config or db setup, but I don't know where or how to check.

```
~/building-database/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
              ^
MongoError: auth failed
    at Object.toError (~/building-database/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:114:11)
```

Here are the setup commands I run in mongo:
```
use building-database
db.users.ensureIndex( { email: 1 }, { unique: true } );
db.users.ensureIndex( { username: 1 }, { unique: true } );
db.buildings.ensureIndex( { "slug.id": 1 }, { unique: true } );
db.buildings.ensureIndex( { location: "2dsphere" } );
```

And here's my config.js:
```
module.exports = {
  "db": {
    "url": "mongodb://user:password@localhost/building-database"
  },
  "email": {
    "report": {
      "fromAddress": "noreply@example.com",
      "subject": "Building report"
    },
    "reset": {
      "fromAddress": "noreply@example.com",
      "subject": "Password reset"
    },
    "verify": {
      "fromAddress": "noreply@example.com",
      "subject": "Please verify your account"
    }
  },
  "session": {
    "secret": "secret"
  }
};
```

**Comment by meetar** [comment]
Could you list the steps you currently take to get the app up and running from a fresh clone?

**Comment by robhawkes** [comment]
It all looks fine, apart from the Mongo authentication error – my steps are identical to those in the [bash tree of the chef branch](https://github.com/polygon-city/chef-buildingdb/tree/bash). Have you created the `user` account with the pass `password` in Mongo? This isn't for the site, this is for the actual database.

If not, you can see how it's done [here in the bash branch of the chef repo](https://github.com/polygon-city/chef-buildingdb/blob/bash/mongo-setup.js#L2). Or, just remove the "user:password" bit from the `db.url` config and leave your database open.

As an aside, we should look at what the appropriate database roles are for the production website. I don't have much experience with protecting Mongo, though the basics seem simple enough.

**Comment by bcamper** [comment]
cc @baldur as well

**Comment by meetar** [comment]
Yep, that was it – I'd added the user to 'test' instead of 'building-database'.
