### ISSUE TITLE
Prioritize best result in search results and area downloads

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#66]
Re: linking alternate models of same building:

For the record: in discussion, we came to the conclusion that we wouldn't officially link alternate models of the same building together, but tune search results to prioritize the best result in a given area (most downloaded, Editor's Pick, or some other metric), allow face/vert count filtering in search results, and to incorporate similar ranking methods for bulk/area downloads.

**Comment by robhawkes** [comment]
Related to #38 and #41, the latter which has recently added a basic "editor's pick" feature.

**Comment by robhawkes** [comment]
4e590fb highlights the picked buildings in the browse and search results via a different background colour.

**Comment by robhawkes** [comment]
Leaving myself a note that highlighted buildings need to be prioritised in the new API endpoints added by #22.

**Comment by robhawkes** [comment]
a56d06b prioritises highlighted buildings in bulk API requests.
