### ISSUE TITLE
scale not being saved?

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#68]
to reproduce:
upload the house.dae file, set a location and a scale, and save.

result: on the resulting buildings page, the building is shown at the uploaded scale, not at the adjusted scale.

**Comment by robhawkes** [comment]
Good catch. Seems I've been using SketchUp models which already have good scaling so although the scaling does save in the database, I didn't notice that the building page 3D viewer isn't honouring the scale in the database (even though it's set from the database in the KML).

I may have to implement the slightly hacky fix used in `/add/location` until ViziCities core reaches a point where model scaling can be overridden within the platform API.

**Comment by robhawkes** [comment]
864a0dd implements a scaling fix for the building page based on the same solution on the `/add/location` endpoint.

**Comment by robhawkes** [comment]
I'm going to close this, assuming the fix holds. I actually improved it today so it's a little more robust and the delay has been removed.
