### ISSUE TITLE
adjust map scale on building page to accommodate model

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#69]
Small buildings are very hard to see, and the map tile isn't zoom-in-able. Perhaps we could either allow zooming or change the scale of the displayed map automatically based on the bbox of the model.

![screen shot 2015-02-13 at 2 17 23 pm](https://cloud.githubusercontent.com/assets/459970/6193624/43c19d7e-b38b-11e4-8151-f5c6aa3a3fe3.png)

**Comment by robhawkes** [comment]
1c87151 is an interim fix that provides better scaling of the ViziCities view on the building page. It's not perfect but it's far better!

**Comment by robhawkes** [comment]
078f070 adds a fix that fits the `/add/location` view to the building. This will be improved further once buildings get centred properly.

**Comment by robhawkes** [comment]
Closing as this has been fixed by various changes in v1, including centring of buildings on the plinth.
