### ISSUE TITLE
Store models on S3

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#72]
Building models should be stored on S3 instead of the local filesystem.

**Comment by bcamper** [comment]
If we add credentials to the config file, chef can provision them upon deploy.

**Comment by robhawkes** [comment]
The [s3 NPM module](https://www.npmjs.com/package/s3) looks to be pretty decent, and well updated. I'll look into this.

**Comment by robhawkes** [comment]
Ok, so the s3 module was a waste of time as uploads don't work so I went with the official [aws-sdk](http://aws.amazon.com/sdk-for-node-js/) module which works just fine.

I've got S3 uploading working on a local branch, though it has introduced a whole world of pain in other parts of the system. For example, the 3D view on `/add/location` is broken as the missing-material fix didn't account for the latency of a slow Internet connection (eg. mine). I'm going to have to re-think that fix before we can push the S3 changes.

**Comment by robhawkes** [comment]
If you agree, I'd be keen to roll this in as is seeing as the bugs this introduces aren't technically related to the S3 integration. Instead, I'll raise those bugs in other tickets as the same situation will occur when the site is hosted non-locally (it's a latency thing on a bad Internet connection, nothing to do with S3).

**Comment by bcamper** [comment]
Sounds good to me, I'd like to start getting S3 config setup for the eventual production env.

**Comment by robhawkes** [comment]
ae60b2d merges the move to model files being hosted on S3. You'll want to add the new S3 config options [as detailed in the sample configuration file](https://github.com/polygon-city/building-database/blob/master/config/config.sample.js#L5). We're using the official `aws-sdk` module so you can find more information on the options [in their documentation](http://aws.amazon.com/sdk-for-node-js/).

To clarify, the system will no longer work locally and requires an S3 account to be set up for buildings to be successfully added.

I'll close this issue and we can reopen new ones for specific changes and bugs.

**Comment by meetar** [comment]
Cooool – can't wait!
…but while I do, would there happen to be a simple way to disable this for
testing, short of rolling back the commit?

**Comment by robhawkes** [comment]
Unfortunately not as I had to change quite a lot of the process for adding a building to handle remote uploading and the lack of having local files on the system. In hindsight, I wish I'd started with remote files first as we'd have naturally fallen into the need for a local testing options alongside that.

Theoretically, we could override the [`uploadFileS3` method](https://github.com/polygon-city/building-database/blob/master/controllers/building.js#L692) when on a development environment to fake an upload to S3 and instead store the file locally and return a local path (rather than an S3 URL). I'm not entirely sure if it'll be as simple as that in practice mind you.
