### ISSUE TITLE
/browse: scroll wheel zoom doesn't work when cursor over map overlay divs

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#77]
To reproduce:
- navigate to the /browse map
- select a building node
- position cursor over the "browse-map-overlay" popup info div or the "col-4 details" div
- use scroll wheel

Result:
scroll wheel activity scrolls the page

Expected result:
map will zoom in/out with scroll wheel

**Comment by robhawkes** [comment]
This is a side-effect of the new footer that I added last week. I'm going to close this issue under the assumption that it will be solved by a solution to #80.
