### ISSUE TITLE
Can't log in with default user

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#78]
To reproduce:
- follow steps in https://github.com/polygon-city/building-database/blob/master/README.md
- attempt to log in with "user"/"password"

Result:
- Page reports "User not found"

Notes:
Running `show users` in mongo produces:
```
> show users
{
	"_id" : "building-database.user",
	"user" : "user",
	"db" : "building-database",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "building-database"
		},
		{
			"role" : "dbAdmin",
			"db" : "building-database"
		}
	]
}
```

**Comment by meetar** [comment]
Not sure this is a real bug, more likely the setup process needs updating

**Comment by robhawkes** [comment]
The user/password setup in the readme is to [create an admin for the database](http://docs.mongodb.org/manual/tutorial/add-user-administrator/), not for Polygon City. You won't be able to login with this user, it's just for an authenticated connection to the database. On first load, there aren't any Polygon City users, you'll need to register one through `/signup`.

**Comment by meetar** [comment]
Got it, thanks!
