### ISSUE TITLE
Limit map to window height

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#80]
Should the map be limited to the window height, to prevent the possibility of scrolling as seen in #77?

**Comment by robhawkes** [comment]
The footer I added last week has caused the full-window maps to have a scrollbar. I need to have a little think about the best way to fix this on these pages, though it shouldn't be a problem (I'm assuming some clever CSS positioning).

**Comment by robhawkes** [comment]
6042f1b adds some CSS to keep the new footer while preventing a scrollbar when the browser window is large enough to display all the content. If not, a scrollbar is displayed because otherwise the content is cut off and the lack of scrollbar prevents you from accessing it.

**Comment by meetar** [comment]
>  when the browser window is large enough to display all the content

Right, I suppose my question has to do less with the browser mechanics than with the page design itself. On my machine, I'm seeing the scrollbar kick in at a window height of 1215px, primarily (afaict) due to the "building-map" div's min-height of 1150px, and the "browser-map" div's min-height of 1000px. Would the design as it stands be able to accommodate, say, a few hundred pixels of flex, to account for a broader range of window heights?
