### ISSUE TITLE
failed to connect to [localhost:27017]

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#86]
Current status:
- mongod starts with: `2015-02-27T13:17:08.396-0500 [initandlisten] waiting for connections on port 27017`
- http://localhost:3000 times out with `http://localhost:3000/ net::ERR_CONNECTION_REFUSED`
- mongodb shows no error, grunt says:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/pjrich/work/building-database/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/pjrich/work/building-database/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/pjrich/work/building-database/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by robhawkes** [comment]
Hmm. What's the `db.url` value in your config file?

**Comment by meetar** [comment]
I've tried both

    "url": "mongodb://user:password@localhost/building-database"

and

    "url": "mongodb://user:password@localhost:27017/building-database"

**Comment by meetar** [comment]
Just added '127.0.0.1 localhost' to my /private/etc/hosts file, and I now
have the home page up with no css. (Don't understand how it wasn't in there
already, or how all of my other localhosted demos have been working if that
was the trouble…)

**Comment by meetar** [comment]
Correction – the css is loaded but empty.

**Comment by meetar** [comment]
Just noticed in grunt output:

```
Running "sass:dist" (sass) task
Warning: /building-database/node_modules/node-neat/node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/helpers/font-source-declaration:29: expected 'in' keyword in @each directive
 Used --force, continuing.
```

**Comment by robhawkes** [comment]
Hmm, that's odd. It's as if some dependency isn't installed, or something else is interfering. Is this on Mac? What happens if you delete `node_modules` within the project directory and re-run `npm install`?

For the record, the SASS generation works fine for me so hopefully we can work out what's different:

```
Running "sass:dist" (sass) task
File public/style/main.css created.
```

**Comment by meetar** [comment]
The sass bug is apparently this one:

https://github.com/sass/node-sass/issues/263

and is fixed here with:

+ "grunt-sass": "^0.18.0",
+ "node-sass": "1.0.3",

Pushed here:

https://github.com/polygon-city/building-database/commit/c4f7c4a619ca865781002d20629300e15f18ff5f
