### ISSUE TITLE
S3 upload issues

### ISSUE THREAD

**Issue by bcamper** [polygon-city/building-database#87]
Seeing what look like a couple issues with the new S3 integration. I do see most of the model files created in my S3 bucket, but the model is not loading in the app, and I see a couple issues:

1: The model paths for `zip` seem to point to the right URLs, but the paths for `raw` look hardcoded to the EU region. Perhaps we need a `region` config setting?

```
  "models" : { "zip" : [ 
      { "type" : "obj",
        "path" : "https://s3.amazonaws.com/dev.polygon.city/model-files/f0239331-c8ae-4bd0-8b9c-16fe28e47c4f/zip/undefined",
        "_id" : ObjectId( "54f0b98c5e4eb64d6150ca69" ),
        "fileSize" : 764 }, 
      { "type" : "dae",
        "path" : "https://s3.amazonaws.com/dev.polygon.city/model-files/f0239331-c8ae-4bd0-8b9c-16fe28e47c4f/zip/undefined",
        "_id" : ObjectId( "54f0b98c5e4eb64d6150ca6a" ),
        "fileSize" : 1616 } ],
    "raw" : [ 
      { "type" : "dae",
        "path" : "https://polygoncity-test.s3-eu-west-1.amazonaws.com/model-files/f0239331-c8ae-4bd0-8b9c-16fe28e47c4f/raw/40b70db2fa9f26bd763f8881f4c39d50.dae",
        "_id" : ObjectId( "54f0b98b5e4eb64d6150ca67" ),
        "fileSize" : 6076 }, 
      { "type" : "obj",
        "path" : "https://polygoncity-test.s3-eu-west-1.amazonaws.com/model-files/f0239331-c8ae-4bd0-8b9c-16fe28e47c4f/raw/40b70db2fa9f26bd763f8881f4c39d50.obj",
        "_id" : ObjectId( "54f0b98b5e4eb64d6150ca68" ),
        "fileSize" : 1271 } ] },
```

2: In the S3 console, it seems the `raw` files are being created correctly, but the `zip` files may not be. `raw` files:

https://s3.amazonaws.com/dev.polygon.city/model-files/f0239331-c8ae-4bd0-8b9c-16fe28e47c4f/raw/40b70db2fa9f26bd763f8881f4c39d50.dae
https://s3.amazonaws.com/dev.polygon.city/model-files/f0239331-c8ae-4bd0-8b9c-16fe28e47c4f/raw/40b70db2fa9f26bd763f8881f4c39d50.obj

`zip` directory only has a single file called `undefined`, though the file size suggests that the file content itself may be correct:

https://s3.amazonaws.com/dev.polygon.city/model-files/f0239331-c8ae-4bd0-8b9c-16fe28e47c4f/zip/undefined

**Comment by robhawkes** [comment]
I see this too – I'll have a look on Monday. The hard-coded stuff is easy to sort out, though I'm unsure why the zips are empty just yet.

**Comment by robhawkes** [comment]
c32cea9 fixes the zip issue (it was caused by the move to S3) and also adds `s3.region` to the config – just fill that with your region ("us-east-1" ?) and it'll be good.

**Comment by robhawkes** [comment]
Ps. Confirm that this has fixed it for you and I'll close the issue if so.

**Comment by bcamper** [comment]
@robhawkes I had lingering problems with that path logic, I think due to inconsistencies in the way US-east-1 vs. other regions are handled :/ (covered in the "Important" section here: http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html).

I'm trying this alternate, which doesn't require S3 region or a http protocol in the URL: https://github.com/polygon-city/building-database/commit/7d66700e44aed081450cf863c925cf71f592bb3a

I think this should work for all S3 regions, and I was separately having an issue locally when https was required, but I think that schemeless URLs should work. I tried to verify that the paths to your EU bucket worked too, but can you give it a try to confirm/deny?

**Comment by robhawkes** [comment]
Cool! I didn't know about those S3 URLs, they're much nicer. I noticed you added one of them; cb8fc6f adds it for for the zip files too. It all works fine for my EU bucket which is good (and weird – what's the point of the region URLs?).

Is S3 working ok for you now?

**Comment by bcamper** [comment]
I really can't explain the strange nature of S3 URLs, I'm going to go with, "legacy" :)

All the URLs seem to work for me now! Closing.
