### ISSUE TITLE
confirmation of verification

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#88]
Currently when one verifies a signup, the link in the verification email goes to the front page of the app – perhaps a notification could be added to show that the link had an effect, and confirmation was achieved?

**Comment by bcamper** [comment]
Ah yes - @robhawkes, I've never really done any serious node web-app development - is there a "flash message" concept (like built into Rails)?

**Comment by robhawkes** [comment]
Yeah, I can work in a flash message for the homepage. We use them around most of the interaction-heavy areas of the site but I hadn't added them to the homepage for some reason.

**Comment by robhawkes** [comment]
4c2085b adds flash messages to the homepage, with a message specifically added after verification succeeds.
