### ISSUE TITLE
Improve ViziCities integration

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/building-database#9]
Right now the ViziCities integration is held together with duct tape and a lot of crossed fingers. It works but a lot of the manual hacks should be integrated into the core ViziCities platform, or at least exposed via a more intuitive API.

Also, collada output needs to be improved to better handle the rotation and scale provided within the KML input (or elsewhere).

**Comment by robhawkes** [comment]
Need to fix / disable keyboard controls as when you currently press the arrow keys anywhere else on the page (eg. in a text field) it moves the 3D view around.

**Comment by meetar** [comment]
Moving your last comment to a new issue for tracking

**Comment by robhawkes** [comment]
Closing this as it's super vague and the ViziCities integration has improved dramatically since December. We can open specific issues for ViziCities issues as they arise.
