### ISSUE TITLE
set location hangs on invalid files

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#90]
- [x] objs with weird normals (tour.obj + tour.obj.zip)
- [x] objs with broken material definitions (essex.zip)

After uploading these models, the Set Location page loads, then freezes in Chrome with an Aw Snap.

…I don't know for sure that these issues are the cause of the crash, but MeshLab complains when I import them.

The app continues to run with no errors, although I can't upload any files at all afterward.

**Comment by robhawkes** [comment]
It's possible that the invalid models are crashing the Three.js collada output. I'll have a look to see if there's a way for it to fail without locking up the browser.

**Comment by robhawkes** [comment]
So it looks like the Three.js Editor loads tour.obj without a problem. Perhaps the assimp conversion to collada is introducing an error. Either way, the collada output shouldn't crash this way – that needs to be fixed.

**Comment by robhawkes** [comment]
As per yesterday's call, I'm going to look at replacing the collada ViziCities output with something like OBJ to see if that solves some of our issues.

**Comment by robhawkes** [comment]
Barring the non-0 origin point of the tour.obj model (causing it to float), that one doesn't crash any more and looks kinda cool!

**Comment by robhawkes** [comment]
@meetar Can you test Essex.zip with this new change? My net is horrific so an 18MB upload to S3 (and download back to the viewer) will take forever and a day.

**Comment by meetar** [comment]
It uploaded! … but then it sank :/

![screen shot 2015-03-12 at 11 25 48 am](https://cloud.githubusercontent.com/assets/459970/6621042/a2ccdf0c-c8aa-11e4-8f99-88714cd58d8e.png)

**Comment by robhawkes** [comment]
Haha, well at least the upload issue has gone now. I'm still not sure how often we'll encounter the need to remap a model's Y-origin but I know we've discussed it in the past. I'm going to close this as fixed and we can raise the origin stuff again for v2, unless we find it a big problem with building models (I haven't noticed it yet).

**Comment by bcamper** [comment]
![classicbattleship](https://cloud.githubusercontent.com/assets/16733/6641708/e95038a4-c975-11e4-83b6-d613155971d5.jpg)
