### ISSUE TITLE
overpass error

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#96]
Currently not reproducible – on initial load of the "set location" page, a javascript alert appeared:

```
The page at localhost:3000 says:

An error occured during the execution of the overpass query!
<p>Request rejected. (e.g. server not found, request blocked by browser addon, request redirected, internal server errors, etc.)</p><p>Error-Code: error (0)</p>
```

…I'll keep an eye out for this, don't know that any action is required except possibly a more friendly error?

**Comment by robhawkes** [comment]
b745baf removes the Overpass alerts – no idea why they chose those over logging. Let me know if you see it again.
