### ISSUE TITLE
Initial scale on tiny models

### ISSUE THREAD

**Issue by meetar** [polygon-city/building-database#99]
Essex.zip comes in at a scale of `0.6804606524581953` but isn't viewable on the screen until a scale of about 100. Would this be related to the internal scale of the essex.zip model?

I suppose this could also be the cause of #97 – if the model comes in tiny, the auto-zoom on the Building Info page might cause wacky perspectives.

Some kind of minimum limit on initial model scale, or maximum limit on the auto-zoom, or both, might help this… and does https://github.com/polygon-city/building-database/commit/1c8715171212f35e71f67be7070258e4a5ee76d9 apply to the Set Building Location page as well, or just the Building Info page?

Additionally, once you set the scale of the model (in this case, I set it to 120), on the Building Info page the viewing tile is tiny:
![screen shot 2015-03-12 at 11 55 55 am](https://cloud.githubusercontent.com/assets/459970/6621760/e5cbdcb4-c8ae-11e4-9469-dac94290fb9b.png)

…I'm guessing these issues are all related, if they're separate we can split them.

**Comment by robhawkes** [comment]
Yeah, this will be related to the internal unit scale for essex.zip – basically ViziCities assumes that the units are in metres, or near enough so you can at least see it and scale manually. This isn't really something we can avoid as technically the units in essex.zip are incompatible with how we'd expect a building to be created (something to go in the guidelines?).

Regardless, some kind of cap on the max and min zoom makes sense to at least avoid the quirks at the far ends of the scale. The logic is slightly different on the building page compared to `/add/location` (as they visualise in different ways) so I'll take a look at how to improve them both.

**Comment by robhawkes** [comment]
bc66614 adds a zoom cap that should help with the visual issues resulting from models that are far too large (at 120, the Essex model is borough-sized). As mentioned in #97, this is more an issue with the building model being too large than the camera not supporting it. We should look into ways to detect and prevent models being added that are clearly too large to be a single building.

**Comment by robhawkes** [comment]
e7abaa3 fixes the zoom on `/add/location` when looking at a really small object.
